include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "build/**"
    - "script/**"
    - "**/*.g.dart"

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    number-of-methods: 10
    weight-of-class: 0.33
    maintainability-index: 50
    
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - always-remove-listener
    - avoid-unused-parameters
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - double-literal-format
    - prefer-const-border-radius
    - prefer_extracting_callbacks
    - member-ordering-extended
    - prefer-extracting-callbacks
    - no-object-declaration
  anti-patterns:
    - long-method
    - long-parameter-list

linter:
  rules:
    public_member_api_docs: true
    avoid_print: true 
    prefer_single_quotes: true 
    noop_primitive_operations: true
    always_use_package_imports: true