name: water_tracker
version: "0.0.1-dev.0"
description: App for water tracking
publish_to: none

dependencies:
  elementary: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  provider: ^6.0.1

dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^4.7.0
  elementary_test: ^1.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  surf_lint_rules: ^1.4.1

environment:
  sdk: ">=2.14.0-0 <3.0.0"

flutter:
  generate: true 
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
